### ISSUE TITLE
Create checklist of client stories

### ISSUE THREAD

**Issue by ibraghada** [go3three/CodeWarsTracker#1]
* [x] Link an existing Google application form of codecamp participants with Codewars website.
* [x] Check the progress of each applicant on Codewars (scores to be updated on a daily basis).
* [x] Send a reminder for applicants not making progress on Codewars.

**Comment by mohanagy** [comment]
Done
